title: Irewole Boluwatife # your name (or website title) here
logo: "tifeh.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Analyst 
  <br><br>
  Mechanical Engineer 
  <br><br>
  <a href="https://www.linkedin.com/in/boluwatife-irewole-8083a81a4/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
